# Generated by Django 5.2.6 on 2025-11-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='descripcion',
            field=models.TextField(blank=True, default='Descripción'),
        ),
    ]
