# Generated by Django 5.2.6 on 2025-11-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_descripcion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_img',
            name='imagen',
            field=models.ImageField(blank=True, default='Bin2bin.png', upload_to='imagenes/'),
        ),
    ]
