# Generated by Django 5.2.6 on 2025-11-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_img_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_img',
            name='imagen',
            field=models.ImageField(blank=True, default='imagenes/Bin2bin.png', upload_to='imagenes/'),
        ),
    ]
