# Generated by Django 5.2.6 on 2025-09-18 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inte', to=settings.AUTH_USER_MODEL)),
                ('pk_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publi.publi')),
                ('publicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
