# Generated by Django 5.2.6 on 2025-10-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0002_interesado'),
    ]

    operations = [
        migrations.AddField(
            model_name='publi',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
