# Generated by Django 5.2.6 on 2025-10-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0003_publi_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publi',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes/'),
        ),
    ]
