# Generated by Django 5.2.6 on 2025-10-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0005_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='publi',
            name='categorias',
            field=models.ManyToManyField(to='publi.categoria'),
        ),
    ]
