# Generated by Django 5.2.6 on 2025-11-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0006_publi_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='publi',
            name='imagen2',
            field=models.ImageField(blank=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='publi',
            name='imagen3',
            field=models.ImageField(blank=True, upload_to='imagenes/'),
        ),
    ]
