# Generated by Django 5.2.6 on 2025-11-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0007_publi_imagen2_publi_imagen3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publi',
            name='descripcion',
            field=models.TextField(blank=True, max_length=110),
        ),
        migrations.AlterField(
            model_name='publi',
            name='titulo',
            field=models.CharField(max_length=25),
        ),
    ]
