# Generated by Django 5.2.6 on 2025-11-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0008_alter_publi_descripcion_alter_publi_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publi',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
